<Project>
  <PropertyGroup>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestorePackagesPath>$(MSBuildThisFileDirectory)artifacts/packages</RestorePackagesPath>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
